port: 5000
router_settings:
  routing_strategy: simple-shuffle
  cooldown_time: 30
  allowed_fails: 2
  num_retries: 2
  timeout: 45
  enable_pre_call_checks: false
  ignore_cooldown_on_fallbacks: true
  max_params_filter: 0 # 0 = disabled; 120 = filter <=120B; 130 = filter <=130B
